// Code generated by aru model:build from model.go. DO NOT EDIT.

package skeleton

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Skeletons starts a query on the table of Skeleton, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Skeletons(db model.DB) *SkeletonQuery { return &SkeletonQuery{b: skeletonTable.Query(db)} }

// SkeletonQuery is a query on the table of Skeleton.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Skeleton rows or a value; there is
// no way to run one without a Grant.
type SkeletonQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *SkeletonQuery) Base() *model.Builder { return q.b }

// New returns an empty Skeleton on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *SkeletonQuery) New() (*Skeleton, error) {
	e, err := q.b.NewModelInstance(nil)
	return skeletonOf(e), err
}

// SkeletonCollection is rows of Skeleton, as a query returns them.
type SkeletonCollection []*Skeleton

// SkeletonCollectionOf converts rows of the table of Skeleton. A nil input is a nil
// collection.
func SkeletonCollectionOf(rows model.Rows) SkeletonCollection {
	if rows == nil {
		return nil
	}
	out := make(SkeletonCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Skeleton)
	}
	return out
}

func skeletonOf(e model.Entity) *Skeleton {
	row, _ := e.(*Skeleton)
	return row
}

// skeletonColumn turns a closure over SkeletonQuery into one over the core builder, so
// passing func(*SkeletonQuery) where a column goes adds a parenthesised group.
func skeletonColumn(column any) any {
	if group, ok := column.(func(*SkeletonQuery)); ok {
		return func(b *model.Builder) { group(&SkeletonQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *SkeletonQuery) Clone() *SkeletonQuery { return &SkeletonQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*SkeletonQuery) in place of the column adds a group.
func (q *SkeletonQuery) Where(column any, args ...any) *SkeletonQuery {
	q.b.Where(skeletonColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*SkeletonQuery) in place of the column adds a group.
func (q *SkeletonQuery) OrWhere(column any, args ...any) *SkeletonQuery {
	q.b.OrWhere(skeletonColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *SkeletonQuery) WhereNot(column any, args ...any) *SkeletonQuery {
	q.b.WhereNot(skeletonColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *SkeletonQuery) OrWhereNot(column any, args ...any) *SkeletonQuery {
	q.b.OrWhereNot(skeletonColumn(column), args...)
	return q
}

func (q *SkeletonQuery) WhereIn(column any, values []any) *SkeletonQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *SkeletonQuery) WhereNotIn(column any, values []any) *SkeletonQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *SkeletonQuery) WhereNull(columns ...any) *SkeletonQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *SkeletonQuery) WhereNotNull(columns ...any) *SkeletonQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *SkeletonQuery) WhereBetween(column any, from, to any) *SkeletonQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *SkeletonQuery) WhereColumn(first any, args ...any) *SkeletonQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *SkeletonQuery) WhereKey(id any) *SkeletonQuery {
	q.b.WhereKey(id)
	return q
}

func (q *SkeletonQuery) WhereExists(callback func(*query.Builder)) *SkeletonQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *SkeletonQuery) WhereNotExists(callback func(*query.Builder)) *SkeletonQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *SkeletonQuery) WhereHas(relation string, callback func(*query.Builder)) *SkeletonQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *SkeletonQuery) OrWhereHas(relation string, callback func(*query.Builder)) *SkeletonQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *SkeletonQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *SkeletonQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *SkeletonQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *SkeletonQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *SkeletonQuery) WhereRelation(relation string, column any, args ...any) *SkeletonQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *SkeletonQuery) OrWhereRelation(relation string, column any, args ...any) *SkeletonQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *SkeletonQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *SkeletonQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *SkeletonQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *SkeletonQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *SkeletonQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *SkeletonQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *SkeletonQuery) OrHas(relation, operator string, count int) *SkeletonQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *SkeletonQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *SkeletonQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *SkeletonQuery) OrDoesntHave(relation string) *SkeletonQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *SkeletonQuery) Select(columns ...any) *SkeletonQuery {
	q.b.Select(columns...)
	return q
}

func (q *SkeletonQuery) AddSelect(columns ...any) *SkeletonQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *SkeletonQuery) SelectRaw(expression string, bindings ...any) *SkeletonQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *SkeletonQuery) Join(table any, first any, args ...any) *SkeletonQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *SkeletonQuery) GroupBy(groups ...any) *SkeletonQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *SkeletonQuery) OrderBy(column any, direction ...string) *SkeletonQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *SkeletonQuery) OrderByDesc(column any) *SkeletonQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *SkeletonQuery) Latest(column ...string) *SkeletonQuery {
	q.b.Latest(column...)
	return q
}

func (q *SkeletonQuery) Oldest(column ...string) *SkeletonQuery {
	q.b.Oldest(column...)
	return q
}

func (q *SkeletonQuery) Limit(value int) *SkeletonQuery {
	q.b.Limit(value)
	return q
}

func (q *SkeletonQuery) Offset(value int) *SkeletonQuery {
	q.b.Offset(value)
	return q
}

func (q *SkeletonQuery) ForPage(page, perPage int) *SkeletonQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *SkeletonQuery) With(relations ...string) *SkeletonQuery {
	q.b.With(relations...)
	return q
}

func (q *SkeletonQuery) WithCount(relations ...string) *SkeletonQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *SkeletonQuery) WithExists(relation string) *SkeletonQuery {
	q.b.WithExists(relation)
	return q
}

func (q *SkeletonQuery) WithSum(relation, column string) *SkeletonQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *SkeletonQuery) WithAvg(relation, column string) *SkeletonQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *SkeletonQuery) WithMin(relation, column string) *SkeletonQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *SkeletonQuery) WithMax(relation, column string) *SkeletonQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *SkeletonQuery) Without(relations ...string) *SkeletonQuery {
	q.b.Without(relations...)
	return q
}

func (q *SkeletonQuery) WithoutGlobalScope(identifier string) *SkeletonQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *SkeletonQuery) WithoutGlobalScopes(identifiers ...string) *SkeletonQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *SkeletonQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (SkeletonCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return SkeletonCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *SkeletonQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Skeleton, error) {
	e, err := q.b.First(ctx, g, columns...)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Skeleton, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Skeleton, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Skeleton, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Skeleton, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Skeleton, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Skeleton, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Skeleton, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (SkeletonCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return SkeletonCollectionOf(rows), err
}

func (q *SkeletonQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Skeleton, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Skeleton, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Skeleton, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Skeleton, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return skeletonOf(e), err
}

func (q *SkeletonQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (SkeletonCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return SkeletonCollectionOf(rows), meta, err
}

func (q *SkeletonQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (SkeletonCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return SkeletonCollectionOf(rows), meta, err
}

func (q *SkeletonQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (SkeletonCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return SkeletonCollectionOf(rows), meta, err
}

func (q *SkeletonQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(SkeletonCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(SkeletonCollectionOf(rows), page)
	})
}

func (q *SkeletonQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Skeleton, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(skeletonOf(e), index)
	})
}

func (q *SkeletonQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Skeleton, error] {
	return func(yield func(*Skeleton, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(skeletonOf(e), err) {
				return
			}
		}
	}
}

func (q *SkeletonQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *SkeletonQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *SkeletonQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *SkeletonQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *SkeletonQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *SkeletonQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *SkeletonQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *SkeletonQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *SkeletonQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *SkeletonQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *SkeletonQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *SkeletonQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *SkeletonQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *SkeletonQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *SkeletonQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *SkeletonQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *SkeletonQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *SkeletonQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *SkeletonQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c SkeletonCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c SkeletonCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c SkeletonCollection) Find(key any) *Skeleton { return skeletonOf(c.Rows().Find(key)) }

func (c SkeletonCollection) FindOrFail(key any) (*Skeleton, error) {
	e, err := c.Rows().FindOrFail(key)
	return skeletonOf(e), err
}

func (c SkeletonCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c SkeletonCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c SkeletonCollection) Only(keys ...any) SkeletonCollection {
	return SkeletonCollectionOf(c.Rows().Only(keys...))
}

func (c SkeletonCollection) Except(keys ...any) SkeletonCollection {
	return SkeletonCollectionOf(c.Rows().Except(keys...))
}

func (c SkeletonCollection) Unique() SkeletonCollection {
	return SkeletonCollectionOf(c.Rows().Unique())
}

func (c SkeletonCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c SkeletonCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c SkeletonCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c SkeletonCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (SkeletonCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return SkeletonCollectionOf(rows), err
}

func (c SkeletonCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Skeleton; it shadows the untyped one the
// embedded model promotes.
func (row *Skeleton) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Skeleton, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return skeletonOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Skeleton) Replicate(except ...string) (*Skeleton, error) {
	e, err := row.Model.Replicate(except...)
	return skeletonOf(e), err
}
